version: '3'
services:
  #Backend
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
  #Frontend
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - BACKEND_URL=${backend}
    depends_on:
      - redis
  redis:
    image: redis:6.2.2
    container_name: redis
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
