version: '3'
services:
  #Backend
  # backend:
  #   container_name: backend
  #   build: ./backend
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./backend/src:/app/src
  #     - /app/node_modules
  #   env_file:
  #     - ./backend/.env
  redis:
    image: redis:6.2.2
    container_name: redis
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
