version: '3'
services:
  #Backend
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./backend/.env
